import { createHash, randomBytes } from "node:crypto";
import { getFirestore } from "firebase-admin/firestore";
import { getStorage } from "firebase-admin/storage";
import { HttpsError, onCall } from "firebase-functions/v2/https";
import { z } from "zod";

import {
  ALLOWED_EVIDENCE_TYPES,
  ENFORCE_APP_CHECK,
  EVIDENCE_PREFIX,
  MAX_EVIDENCE_BYTES,
  MAX_EVIDENCE_FILES,
  RATE_LIMITS,
  REGION,
  UPLOAD_URL_TTL_MINUTES,
} from "./config.js";
import { logProblem } from "./logging.js";

/** Set by the emulator suite, and by nothing in production. */
const IN_EMULATOR = process.env.FUNCTIONS_EMULATOR === "true";
import { consumeRateLimit } from "./rateLimit.js";

/**
 * Taken from the SDK rather than imported from `@google-cloud/storage`, which
 * ships both a CJS and an ESM build with structurally incompatible types.
 */
type Bucket = ReturnType<ReturnType<typeof getStorage>["bucket"]>;

/**
 * Which folder a submission's evidence belongs in.
 *
 * Derived rather than stored, so `submitReport` can recompute the only folder
 * it will accept instead of trusting the paths it is handed.
 *
 * **The device uid is in the hash, not just the key.** The idempotency key is
 * generated by the client and travels in the clear through two calls — it was
 * never a secret, and a folder derived from it alone let anyone who saw one
 * obtain signed URLs into someone else's evidence folder, and write there
 * before its author had sent anything. The uid comes from a token the caller
 * cannot forge, so the folder now belongs to a device rather than to whoever
 * happens to know a string.
 */
export function evidenceFolderFor(uid: string, idempotencyKey: string): string {
  return createHash("sha256")
    .update(`${uid}:${idempotencyKey}`, "utf8")
    .digest("hex")
    .slice(0, 32);
}

const EXTENSIONS: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
};

/** L'inverse, pour retrouver le type d'un objet depuis son nom. */
const EXTENSION_TYPES: Record<string, string> = Object.fromEntries(
  Object.entries(EXTENSIONS).map(([type, extension]) => [extension, type]),
);

/** An object name nobody can guess, inside the submission's folder. */
export function newEvidencePath(
  uid: string,
  idempotencyKey: string,
  contentType: string,
): string {
  const extension = EXTENSIONS[contentType];
  if (!extension) throw new HttpsError("invalid-argument", "unsupported type");
  const name = randomBytes(16).toString("hex");
  return `${EVIDENCE_PREFIX}/${evidenceFolderFor(uid, idempotencyKey)}/${name}.${extension}`;
}

export const uploadUrlRequest = z.object({
  idempotencyKey: z
    .string()
    .trim()
    .min(16)
    .max(128)
    .regex(/^[A-Za-z0-9_-]+$/),
  contentType: z.enum(ALLOWED_EVIDENCE_TYPES),
  sizeBytes: z.number().int().positive().max(MAX_EVIDENCE_BYTES),
});

/**
 * Why a set of evidence paths cannot be accepted, or an empty list.
 *
 * Called by `submitReport` before it writes anything. Three things are checked,
 * and the first is the one that matters: **the path has to sit in the folder
 * this submission's key derives to.** A well-formed path is not proof it was
 * ever issued, and without this check a caller could reference an object
 * belonging to someone else's report.
 *
 * The other two — the object exists, and its metadata is what was promised —
 * close the gap between what a signed URL binds at issue time and what actually
 * landed in the bucket.
 */
export async function verifyEvidence(
  uid: string,
  idempotencyKey: string,
  paths: string[],
  bucket: Bucket,
): Promise<string[]> {
  if (paths.length === 0) return [];
  if (paths.length > MAX_EVIDENCE_FILES) return ["too_many_files"];

  const expected = `${EVIDENCE_PREFIX}/${evidenceFolderFor(uid, idempotencyKey)}/`;
  const problems: string[] = [];

  await Promise.all(
    paths.map(async (path, index) => {
      if (!path.startsWith(expected)) {
        problems.push(`path_${index}_not_issued_for_this_submission`);
        return;
      }

      const file = bucket.file(path);
      const [exists] = await file.exists();
      if (!exists) {
        problems.push(`path_${index}_missing`);
        return;
      }

      const [metadata] = await file.getMetadata();
      const size = Number(metadata.size ?? 0);
      if (size > MAX_EVIDENCE_BYTES) problems.push(`path_${index}_too_large`);

      // The Storage emulator records every upload as application/octet-stream,
      // whatever the client declares — so this check cannot run locally without
      // rejecting every screenshot. Deployed, a signed URL binds the type at
      // issue time and this re-reads what actually landed.
      if (!IN_EMULATOR) {
        const type = metadata.contentType ?? "";
        if (!ALLOWED_EVIDENCE_TYPES.includes(type as never)) {
          problems.push(`path_${index}_wrong_type`);
        }
      }
    }),
  );

  return problems;
}

/**
 * A URL the console can put in an `<img>` to show one screenshot.
 *
 * Deployed: a signed read URL, valid fifteen minutes. The console shows the
 * evidence, it does not publish it.
 *
 * In the emulator: signing needs a service account the suite does not have, so
 * `getSignedUrl` throws `SigningError` — which surfaced as a bare `INTERNAL`
 * the moment an agent opened any case carrying a screenshot. The emulator
 * assigns each object a download token instead, which serves it over plain
 * HTTP with no Authorization header — the only shape an `<img>` can use.
 */
export async function evidenceReadUrl(
  bucket: Bucket,
  path: string,
): Promise<string> {
  const file = bucket.file(path);

  if (!IN_EMULATOR) {
    const [url] = await file.getSignedUrl({
      version: "v4",
      action: "read",
      expires: Date.now() + UPLOAD_URL_TTL_MINUTES * 60 * 1000,
    });
    return url;
  }

  const [metadata] = await file.getMetadata();
  let token = metadata.metadata?.firebaseStorageDownloadTokens as
    | string
    | undefined;

  // Le type est aussi remis d'aplomb : l'émulateur enregistre tout en
  // application/octet-stream, quel que soit celui déclaré à l'envoi. Les
  // navigateurs devinent, mais une console qui sert ses images avec le bon
  // type est une console qui se comporte comme celle déployée.
  const extension = file.name.slice(file.name.lastIndexOf(".") + 1);
  const declared = EXTENSION_TYPES[extension];
  const wrongType = declared && metadata.contentType !== declared;

  if (!token || wrongType) {
    token ??= randomBytes(16).toString("hex");
    await file.setMetadata({
      ...(wrongType ? { contentType: declared } : {}),
      metadata: { firebaseStorageDownloadTokens: token },
    });
  }

  const host = process.env.FIREBASE_STORAGE_EMULATOR_HOST ?? "127.0.0.1:9199";
  return (
    `http://${host}/v0/b/${bucket.name}/o/${encodeURIComponent(path)}` +
    `?alt=media&token=${token}`
  );
}

/**
 * Hands out one signed URL for one object.
 *
 * The bucket stays closed to clients — `storage.rules` denies everything — and
 * a signed URL carries its own authorisation, scoped to a single object, a
 * single content type and a few minutes. Nothing reaches the bucket that this
 * function did not authorise.
 */
export type SignedUpload = {
  uploadUrl: string;
  storagePath: string;
  /** `PUT` for a signed URL, `POST` for the emulator's own endpoint. */
  method: "PUT" | "POST";
  headers: Record<string, string>;
};

export const requestEvidenceUploadUrl = onCall(
  { region: REGION, enforceAppCheck: ENFORCE_APP_CHECK, memory: "256MiB", timeoutSeconds: 30 },
  async (request): Promise<SignedUpload> => {
    const uid = request.auth?.uid;
    if (!uid) {
      throw new HttpsError("unauthenticated", "anonymous sign-in required");
    }

    const parsed = uploadUrlRequest.safeParse(request.data);
    if (!parsed.success) {
      throw new HttpsError("invalid-argument", "malformed upload request");
    }

    const verdict = await consumeRateLimit(
      getFirestore(),
      "upload_hourly",
      uid,
      RATE_LIMITS.uploadUrlHourly,
    );
    if (!verdict.allowed) {
      logProblem({ event: "upload_rate_limited" });
      throw new HttpsError("resource-exhausted", "too many uploads");
    }

    const { idempotencyKey, contentType } = parsed.data;
    const bucket = getStorage().bucket();
    const storagePath = newEvidencePath(uid, idempotencyKey, contentType);

    if (IN_EMULATOR) {
      // Signing needs a real service account — a `client_email` and a private
      // key — which the emulator suite has neither of. `getSignedUrl` there
      // fails with `Cannot sign data without client_email`, so every report
      // carrying a screenshot died locally while one with a link went through.
      //
      // The emulator exposes its own upload endpoint, and accepts the
      // well-known admin token `owner`. That token means nothing outside the
      // emulator and is worth nothing to anyone: this branch cannot run in
      // production, where `FUNCTIONS_EMULATOR` is unset.
      const host = process.env.FIREBASE_STORAGE_EMULATOR_HOST ?? "127.0.0.1:9199";
      return {
        uploadUrl:
          `http://${host}/v0/b/${bucket.name}/o` +
          `?name=${encodeURIComponent(storagePath)}&uploadType=media`,
        storagePath,
        method: "POST",
        headers: { Authorization: "Bearer owner" },
      };
    }

    const [uploadUrl] = await bucket.file(storagePath).getSignedUrl({
      version: "v4",
      action: "write",
      expires: Date.now() + UPLOAD_URL_TTL_MINUTES * 60 * 1000,
      // Signed into the URL: an upload declaring anything else is refused by
      // Cloud Storage before a byte is written.
      contentType,
    });

    return { uploadUrl, storagePath, method: "PUT", headers: {} };
  },
);
