// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJD5OGj9EMlQRm63jVqu8D00NrHan_hXA',
    appId: '1:576468502948:web:ab03ac4e256ce7b4061931',
    messagingSenderId: '576468502948',
    projectId: 'emc-helpline-e82ef',
    authDomain: 'emc-helpline-e82ef.firebaseapp.com',
    storageBucket: 'emc-helpline-e82ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqyqfNS-zYRfyEvyuJgiWLvMDVgZbsVC4',
    appId: '1:576468502948:android:0e90ebc9da671d0c061931',
    messagingSenderId: '576468502948',
    projectId: 'emc-helpline-e82ef',
    storageBucket: 'emc-helpline-e82ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMEP6jPj4FgKXC0OivLlAf0ddmAFG0PlY',
    appId: '1:576468502948:ios:9c8172a3c04ef8b2061931',
    messagingSenderId: '576468502948',
    projectId: 'emc-helpline-e82ef',
    storageBucket: 'emc-helpline-e82ef.firebasestorage.app',
    iosBundleId: 'com.emchelpline.emcHelpline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMEP6jPj4FgKXC0OivLlAf0ddmAFG0PlY',
    appId: '1:576468502948:ios:9c8172a3c04ef8b2061931',
    messagingSenderId: '576468502948',
    projectId: 'emc-helpline-e82ef',
    storageBucket: 'emc-helpline-e82ef.firebasestorage.app',
    iosBundleId: 'com.emchelpline.emcHelpline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJD5OGj9EMlQRm63jVqu8D00NrHan_hXA',
    appId: '1:576468502948:web:8b5a48e372171faa061931',
    messagingSenderId: '576468502948',
    projectId: 'emc-helpline-e82ef',
    authDomain: 'emc-helpline-e82ef.firebaseapp.com',
    storageBucket: 'emc-helpline-e82ef.firebasestorage.app',
  );
}
